// AUTO-GENERATED by scripts/sync-edge.mjs — edit the original in src/ and re-run `npm run sync:edge`.
export type Lang = 'he' | 'en';
export type UnitSystem = 'original' | 'metric' | 'us';

export type Profile = {
  id: string;
  display_name: string | null;
  language: Lang;
  unit_system: UnitSystem;
  custom_aisles: string[];
};

export type UnitKind = 'volume' | 'mass' | 'count';

// One structured ingredient line. `raw` is always preserved and is the display
// fallback: only lines the parser understood (qty != null) scale/convert/merge.
export type ParsedIngredient = {
  raw: string;
  qty: number | null;
  qtyMax: number | null; // ranges: "1-2" => qty 1, qtyMax 2
  unit: string | null; // canonical unit id ('cup','tbsp','g','unit',...)
  name: string;
  note: string | null;
  group: string | null; // "For the sauce" / "לרוטב" section header
};

export type Step = { text: string; group: string | null };

export type Nutrition = {
  calories: number | null;
  protein: number | null;
  carbs: number | null;
  fat: number | null;
};

export type Recipe = {
  id: string;
  owner_id: string;
  title: string;
  description: string | null;
  image_path: string | null; // storage path (or dataURL in demo mode)
  image_url: string | null; // external image kept from import
  source_url: string | null;
  source_name: string | null;
  prep_min: number | null;
  cook_min: number | null;
  total_min: number | null;
  servings: number | null;
  ingredients: ParsedIngredient[];
  steps: Step[];
  notes: string | null;
  tags: string[];
  nutrition: Nutrition | null;
  favorite: boolean;
  is_public: boolean;
  lang: Lang;
  created_at: string;
  updated_at: string;
};

export type ImportConfidence = 'high' | 'medium' | 'low';

// What the import pipeline hands to the editor.
export type RecipeDraft = Omit<
  Recipe,
  'id' | 'owner_id' | 'created_at' | 'updated_at' | 'image_path' | 'favorite' | 'is_public'
> & { confidence: ImportConfidence };

export type Cookbook = {
  id: string;
  owner_id: string;
  name: string;
  emoji: string | null;
  invite_token: string;
  created_at: string;
};

export type CookbookRecipe = { id: string; cookbook_id: string; recipe_id: string };

export type CookbookMember = {
  id: string;
  cookbook_id: string;
  user_id: string;
  role: string;
  display_name?: string | null;
};

export type GroceryItem = {
  id: string;
  user_id: string;
  name: string;
  normalized_name: string;
  qty: number | null;
  unit: string | null;
  aisle: string;
  recipe_id: string | null;
  recipe_title: string | null;
  checked: boolean;
  created_at: string;
};

export type NewGroceryItem = Omit<GroceryItem, 'id' | 'user_id' | 'created_at' | 'checked'>;

export type PlanSlot = 'breakfast' | 'lunch' | 'dinner' | 'snack';

export type MealPlanEntry = {
  id: string;
  user_id: string;
  plan_date: string; // YYYY-MM-DD
  slot: PlanSlot;
  recipe_id: string;
  servings: number | null;
};

export const PLAN_SLOTS: PlanSlot[] = ['breakfast', 'lunch', 'dinner', 'snack'];
