// AUTO-GENERATED by scripts/sync-edge.mjs — edit the original in src/ and re-run `npm run sync:edge`.
import type { Lang, UnitKind } from './types.ts';

export type UnitDef = {
  id: string;
  kind: UnitKind;
  /** multiplier to the base unit of its kind (ml for volume, g for mass) */
  toBase?: number;
  labels: Record<Lang, string>;
  labelsPlural?: Record<Lang, string>;
};

export const UNITS: Record<string, UnitDef> = {
  // volume (base: ml)
  ml: { id: 'ml', kind: 'volume', toBase: 1, labels: { en: 'ml', he: 'מ״ל' } },
  l: { id: 'l', kind: 'volume', toBase: 1000, labels: { en: 'liter', he: 'ליטר' }, labelsPlural: { en: 'liters', he: 'ליטר' } },
  tsp: { id: 'tsp', kind: 'volume', toBase: 5, labels: { en: 'tsp', he: 'כפית' }, labelsPlural: { en: 'tsp', he: 'כפיות' } },
  tbsp: { id: 'tbsp', kind: 'volume', toBase: 15, labels: { en: 'tbsp', he: 'כף' }, labelsPlural: { en: 'tbsp', he: 'כפות' } },
  cup: { id: 'cup', kind: 'volume', toBase: 240, labels: { en: 'cup', he: 'כוס' }, labelsPlural: { en: 'cups', he: 'כוסות' } },
  // mass (base: g)
  g: { id: 'g', kind: 'mass', toBase: 1, labels: { en: 'g', he: 'גרם' } },
  kg: { id: 'kg', kind: 'mass', toBase: 1000, labels: { en: 'kg', he: 'ק״ג' } },
  oz: { id: 'oz', kind: 'mass', toBase: 28.35, labels: { en: 'oz', he: 'אונקיה' } },
  lb: { id: 'lb', kind: 'mass', toBase: 453.6, labels: { en: 'lb', he: 'פאונד' } },
  // count-ish
  unit: { id: 'unit', kind: 'count', labels: { en: '', he: '' } },
  clove: { id: 'clove', kind: 'count', labels: { en: 'clove', he: 'שן' }, labelsPlural: { en: 'cloves', he: 'שיני' } },
  can: { id: 'can', kind: 'count', labels: { en: 'can', he: 'קופסה' }, labelsPlural: { en: 'cans', he: 'קופסאות' } },
  pkg: { id: 'pkg', kind: 'count', labels: { en: 'package', he: 'חבילה' }, labelsPlural: { en: 'packages', he: 'חבילות' } },
  slice: { id: 'slice', kind: 'count', labels: { en: 'slice', he: 'פרוסה' }, labelsPlural: { en: 'slices', he: 'פרוסות' } },
  pinch: { id: 'pinch', kind: 'count', labels: { en: 'pinch', he: 'קורט' } },
  bunch: { id: 'bunch', kind: 'count', labels: { en: 'bunch', he: 'צרור' } },
};

// Alias -> canonical id. Keys are matched after lowercasing and trimming a
// trailing period; Hebrew geresh/gershayim forms are listed explicitly.
const ALIASES: Record<string, string> = {
  // en volume
  cup: 'cup', cups: 'cup', c: 'cup',
  tablespoon: 'tbsp', tablespoons: 'tbsp', tbsp: 'tbsp', tbsps: 'tbsp', tbs: 'tbsp', tb: 'tbsp',
  teaspoon: 'tsp', teaspoons: 'tsp', tsp: 'tsp', tsps: 'tsp', ts: 'tsp',
  ml: 'ml', milliliter: 'ml', milliliters: 'ml', millilitre: 'ml', millilitres: 'ml',
  l: 'l', liter: 'l', liters: 'l', litre: 'l', litres: 'l',
  // en mass
  g: 'g', gr: 'g', gram: 'g', grams: 'g',
  kg: 'kg', kilo: 'kg', kilos: 'kg', kilogram: 'kg', kilograms: 'kg',
  oz: 'oz', ounce: 'oz', ounces: 'oz',
  lb: 'lb', lbs: 'lb', pound: 'lb', pounds: 'lb',
  // en count
  clove: 'clove', cloves: 'clove',
  can: 'can', cans: 'can', tin: 'can', tins: 'can',
  package: 'pkg', packages: 'pkg', pkg: 'pkg', packet: 'pkg', packets: 'pkg', pack: 'pkg',
  slice: 'slice', slices: 'slice',
  pinch: 'pinch', pinches: 'pinch',
  bunch: 'bunch', bunches: 'bunch',
  piece: 'unit', pieces: 'unit',
  // he volume
  'כוס': 'cup', 'כוסות': 'cup',
  'כף': 'tbsp', 'כפות': 'tbsp',
  'כפית': 'tsp', 'כפיות': 'tsp',
  'מ"ל': 'ml', 'מ״ל': 'ml', 'מל': 'ml',
  'ליטר': 'l', 'ליטרים': 'l',
  // he mass
  'גרם': 'g', 'גר': 'g', "גר'": 'g', 'גר׳': 'g', "ג'": 'g', 'ג׳': 'g',
  'ק"ג': 'kg', 'ק״ג': 'kg', 'קג': 'kg', 'קילו': 'kg', 'קילוגרם': 'kg',
  'אונקיה': 'oz',
  // he count
  'שן': 'clove', 'שיני': 'clove', 'שיניים': 'clove',
  'קופסה': 'can', 'קופסת': 'can', 'קופסא': 'can', 'פחית': 'can',
  'חבילה': 'pkg', 'חבילת': 'pkg', 'שקית': 'pkg', 'אריזה': 'pkg', 'אריזת': 'pkg',
  'פרוסה': 'slice', 'פרוסות': 'slice',
  'קורט': 'pinch',
  'צרור': 'bunch', 'חופן': 'bunch',
  'יחידה': 'unit', 'יחידות': 'unit',
};

export function unitFor(token: string): UnitDef | null {
  const key = token.trim().toLowerCase().replace(/\.$/, '');
  const id = ALIASES[key];
  return id ? UNITS[id] : null;
}

export function unitLabel(id: string | null, qty: number | null, lang: Lang): string {
  if (!id) return '';
  const def = UNITS[id];
  if (!def) return id;
  // plural only above 1 ("2 כפות") — fractions read as singular ("¼ כוס")
  const plural = qty != null && qty > 1 && def.labelsPlural ? def.labelsPlural[lang] : def.labels[lang];
  return plural;
}
