// Copies the pure parser modules into the Supabase edge function folder,
// rewriting imports for Deno (explicit .ts extensions, flat layout). The
// copies are committed so `supabase functions deploy import-recipe` works
// without any build step. Re-run after editing src/lib/parse/*.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const outDir = new URL('../supabase/functions/import-recipe/parse/', import.meta.url);
mkdirSync(outDir, { recursive: true });

const files = [
  { from: '../src/lib/types.ts', to: 'types.ts' },
  { from: '../src/data/units.ts', to: 'units.ts' },
  { from: '../src/lib/parse/duration.ts', to: 'duration.ts' },
  { from: '../src/lib/parse/ingredient.ts', to: 'ingredient.ts' },
  { from: '../src/lib/parse/jsonld.ts', to: 'jsonld.ts' },
  { from: '../src/lib/parse/microdata.ts', to: 'microdata.ts', prefix: '/// <reference lib="dom" />\n' },
];

const rewrites = [
  [/from '\.\.\/types'/g, "from './types.ts'"],
  [/from '\.\.\/\.\.\/data\/units'/g, "from './units.ts'"],
  [/from '\.\.\/lib\/types'/g, "from './types.ts'"],
  [/from '\.\/ingredient'/g, "from './ingredient.ts'"],
  [/from '\.\/duration'/g, "from './duration.ts'"],
];

for (const { from, to, prefix } of files) {
  let code = readFileSync(new URL(from, import.meta.url), 'utf8');
  for (const [re, replacement] of rewrites) code = code.replace(re, replacement);
  const header = `// AUTO-GENERATED by scripts/sync-edge.mjs — edit the original in src/ and re-run \`npm run sync:edge\`.\n`;
  writeFileSync(new URL(to, outDir), header + (prefix ?? '') + code);
  console.log(`synced ${to}`);
}
